name: parqo
channels:
  - defaults
dependencies:
  - ca-certificates=2024.12.31
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.8.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - anyio==4.5.2
    - appnope==0.1.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - attrs==25.1.0
    - babel==2.17.0
    - backcall==0.2.0
    - beautifulsoup4==4.13.3
    - bleach==6.1.0
    - bm25s==0.2.13
    - cachetools==5.5.2
    - certifi==2025.1.31
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - comm==0.2.2
    - contourpy==1.1.1
    - cycler==0.12.1
    - debugpy==1.8.12
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.9
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fastjsonschema==2.21.1
    - filelock==3.16.1
    - fonttools==4.55.3
    - fqdn==1.5.1
    - fsspec==2025.3.0
    - google-auth==2.38.0
    - google-auth-oauthlib==1.0.0
    - greenlet==3.1.1
    - grpcio==1.70.0
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - idna==3.10
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipykernel==6.29.5
    - ipython==8.12.3
    - isoduration==20.11.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - joblib==1.4.2
    - json5==0.10.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.3.5
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - kiwisolver==1.4.7
    - llvmlite==0.41.1
    - markdown==3.7
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.7
    - mistune==3.1.2
    - mpmath==1.3.0
    - multipledispatch==1.0.0
    - multiprocess==0.70.17
    - nbclient==0.10.1
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.1
    - notebook==7.3.2
    - notebook-shim==0.2.4
    - numba==0.58.1
    - numpy==1.24.4
    - oauthlib==3.2.2
    - overrides==7.7.0
    - packaging==24.2
    - pandas==1.5.1
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - pglast==7.3
    - pickleshare==0.7.5
    - pillow==10.4.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - playwright==1.48.0
    - prometheus-client==0.21.1
    - prompt-toolkit==3.0.50
    - protobuf==5.29.3
    - psqlparse==1.0rc7
    - psutil==6.1.1
    - psycopg2==2.9.10
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pycparser==2.22
    - pyee==12.0.0
    - pygments==2.19.1
    - pynndescent==0.5.13
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - python-json-logger==3.2.1
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzmq==26.2.1
    - referencing==0.35.1
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.20.1
    - rsa==4.9
    - salib==1.4.8
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - send2trash==1.8.3
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.6
    - sqlparse==0.5.3
    - stack-data==0.6.3
    - sympy==1.13.3
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - terminado==0.18.1
    - threadpoolctl==3.5.0
    - tinycss2==1.2.1
    - tomli==2.2.1
    - torch==2.2.2
    - torchdrift==0.1.0.post1
    - torchvision==0.17.2
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - types-python-dateutil==2.9.0.20241206
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - umap-learn==0.5.7
    - uri-template==1.3.0
    - urllib3==2.2.3
    - wcwidth==0.2.13
    - webcolors==24.8.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==3.0.6
    - zipp==3.20.2
